### ISSUE TITLE
Error if settings has a C-style comment

### ISSUE THREAD

**Issue by jibbers42** [sadesyllas/explorer-excluded-files#2]
If settings.json has something like `/* I'm a C-style comment */` and you try to run command `Hide Explorer Excluded Files`, then you will get the following...

error: `command 'extension.hideExplorerExcludedFiles' not found`

and in the console:
```
mainThreadExtensionService.ts:110
Activating extension `sadesyllas.explorer-excluded-files` failed:
Unexpected token / in JSON at position 131.
```

**Comment by sadesyllas** [comment]
When parsing a `.json` file it's easy to omit any kind of comment (e.g., when setting user preferences in vs code, the user is the writter, vs code is the reader).

But when writting to e.g. `settings.json`, as this extension does, it's difficult to put the comments back where they were initially written by the user.

That would need something more complex than a simple `JSON.parse` and it's not the purpose of this extension to implement such functionality.
